### PR TITLE
SSH.NET 2023.0.1 update and more tests

### PR DESCRIPTION
**Pull request by Kim-SSi**
Update NuGet packages, including SSH.NET 2023.0.1
Fix compile errors relating to 2023.0.1 changes
Add a text to verify that loading encrypted keys fails with the wrong password

### CODE REVIEW

**Comment by Kim-SSi** [comment]
I can rewrite the test changes to use the ppk v3 options when that is merged is you want me to.

**Comment by darinkes** [comment]
Thank you a lot for the PR, but I want to update SSH.NET in all the extensions at the same time. Easier for me to just think about it once :)
Will update you here, when its done. ppkv3 Support is now merged, will bump the NuGet once SSH.NET is also updated :+1:

**Comment by darinkes** [comment]
I prepared a PR https://github.com/darinkes/SshNet.PuttyKeyFile/pull/5 with SSH.NET 2024.0.1 update and it also contains RSA signature improvements.
To make it work with current OpenSSH Servers, which no longer accept SHA1.

Maybe you can rebase the tests improvements on it.

A second opinion is highly appreciated.

**Comment by Kim-SSi** [comment]
Thanks for the work on PR#5.

**Pull request closed without merging**
